# Generated by Django 3.2.7 on 2021-09-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210920_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
