# Generated by Django 3.2.7 on 2021-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=350)),
                ('category', models.CharField(max_length=50)),
                ('blog_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
